flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- .
extra-deps:
- aeson-1.2.2.0
- attoparsec-0.13.2.0
- base-compat-0.9.3
- case-insensitive-1.2.0.10
- dlist-0.8.0.3
- hashable-1.2.6.1
- integer-logarithms-1.0.2
- megaparsec-6.1.1
- monad-loops-0.4.3
- mtl-2.2.1
- parser-combinators-0.2.0
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.5.2
- tagged-0.8.5
- text-1.2.2.2
- th-abstraction-0.2.6.0
- time-locale-compat-0.1.1.3
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- uuid-types-1.0.3
- vector-0.12.0.1
resolver: ghc-8.2
